### ISSUE TITLE
using the same upstream components multiple times in a project

### ISSUE THREAD

**Issue by Guslington** [theonestack/cfhighlander#101]
The issue is when you use the same component multiple times that is referencing an upstream component. 

For example take a project that manages 2 s3-websites that includes the `s3-cloudfront` component twice.

```ruby
CfhighlanderTemplate do
  Name 's3-website'
  Description "s3-website"

  Component name: 's3cloudfront1', template: 's3-cloudfront'
  Component name: 's3cloudfront2', template: 's3-cloudfront'

end
```

The `s3-cloudfront` component inlines the `cloudfront` component with the name hardcoded to `cloudfront`. https://github.com/theonestack/hl-component-s3-cloudfront/blob/master/s3-cloudfront.cfhighlander.rb#L11

There for the last cloudfront config will overwrite them all causing each s3-website to have the same configuration.

I think the way to resolve this would be to prefix the sub component names with the component name in the project. The same way we handled the config files

```
s3cloudfront1-cloudfront
s3cloudfront2-cloudfront
```

**Comment by aaronwalker** [comment]
@Guslington @toshke yeah I tried to modified the s3-cloudfront component to use the component_name as part of the component name for cloudfront component

something like
```ruby
  Component name: #{component_name}-cdn', template: 'cloudfront@master.snapshot', render: Inline do
    parameter name: "s3bucketOriginDomainName", value: FnGetAtt('Bucket', 'DomainName')
  end
```
but that didn't help since the issue if the cloudfront is pulling its default config

**Comment by rererecursive** [comment]
I just ran into this problem using the `s3-cloudfront` component. My solution was a bit hacky, but it was to give the CloudFront component a custom name, and then give config block a matching name so that they link. For example, using the config:
```yaml
bucket_name: my_bucket
cloudfront_component_name: cloudfrontOne
components:
  cloudfrontOne:
    config:
      ...
```
and these changes to the Highlander component:
```ruby
  Component name: cloudfront_component_name, template: 'cloudfront@master.snapshot', render: Inline do
    parameter name: "s3bucketOriginDomainName", value: FnGetAtt('Bucket', 'DomainName')
  end
```
```
bucket_name: frontend.${EnvironmentName}.${DnsDomain}
cloudfront_component_name: cloudfront
components:
  cloudfront:   # This must match 'cloudfront_component_name'
    config:
      ...
```
I got it to work.
