### ISSUE TITLE
Support publishing additional artifacts 

### ISSUE THREAD

**Issue by aaronwalker** [theonestack/cfhighlander#165]
I would be useful to be able to include additional artifacts in the S3 publish for components. 

Use Case: The api gateway component supports loading a api swagger file from S3 so it would be useful to just include the api swagger definition is the published templates instead of requiring an additional deployment step

maybe something like

```ruby
PublishArtifact file: "my-swagger.yaml", key: "my-swagger-#{component_version}.yaml"
```
The key could be optional

**Comment by aaronwalker** [comment]
@Guslington @toshke thoughts?

**Comment by Guslington** [comment]
@aaronwalker would it be worth exposing the artifact key value to a component

```yaml
Api:
    Type: AWS::ApiGateway::RestApi
    Properties: 
    BodyS3Location: 
        Bucket: distribution_bucket
        Key: artifact_key['name']
```
