### ISSUE TITLE
Support for using conditional on inlined Components

### ISSUE THREAD

**Issue by aaronwalker** [theonestack/cfhighlander#172]
Right now conditional components only works for nested stacks but Ideally you would be able to define something as conditional and if it gets inlined the condition gets added to each resource that gets inlined.

Currently it correct adds the Parameter and Condition definitions in the inlined CloudFormation

Considering the following here component

```ruby
CfhighlanderTemplate do

  Parameters do
    ComponentParam 'RegionCode', 'eu', allowedValues: ['eu', 'us', 'ap']
  end

  Component template: 'a', name: 'a1', render: Inline, conditional: true, enabled: false do
    parameter name: 'RegionCode', value: Ref('RegionCode')
  end

  Component template: 'a', name: 'a2', conditional: true, enabled: false do
    parameter name: 'RegionCode', value: Ref('RegionCode')
  end
    
end
```

and the cfndsl for component a

```ruby
CloudFormation do

  Condition(:EURegion, FnEquals(Ref(:RegionCode), 'eu'))

  SNS_Topic(:SnsTopic) do
    DisplayName FnSub('topic-${RegionCode}')
  end

  SNS_Topic(:SnsTopic2) do
    Condition(:EURegion)
    DisplayName FnSub('topic2-${RegionCode}')
  end
end
```

The compiled template for b should be

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  Enablea1:
    Fn::Equals:
    - Ref: Enablea1
    - 'true'
  Enablea2:
    Fn::Equals:
    - Ref: Enablea2
    - 'true'
  EURegion:
    Fn::And:
    - Condtion: Enablea1
    - Fn::Equals:
      - Ref: RegionCode
      - eu
Resources:
  a2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./a2.compiled.yaml"
      Parameters:
        RegionCode:
          Ref: RegionCode
    Condition: Enablea2
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::Sub: topic-${RegionCode}
    Condition: Enablea1
  SnsTopic2:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::Sub: topic2-${RegionCode}
    Condition: EURegion
Parameters:
  RegionCode:
    Type: String
    Default: eu
    NoEcho: false
    AllowedValues:
    - eu
    - us
    - ap
  Enablea1:
    Type: String
    Default: 'false'
    NoEcho: false
    AllowedValues:
    - 'true'
    - 'false'
  Enablea2:
    Type: String
    Default: 'false'
    NoEcho: false
    AllowedValues:
    - 'true'
    - 'false'
Description: b@latest - vlatest
Outputs:
  CfTemplateUrl:
    Value: "/b.compiled.yaml"
  CfTemplateVersion:
    Value: latest
  a1CfTemplateVersion:
    Value: latest
```
