### ISSUE TITLE
Tagging resources

### ISSUE THREAD

**Issue by Guslington** [theonestack/cfhighlander#73]
I think there needs to be functionality in highlander core to manage tagging on an individual resource level through configuration. 

My example is say the ecs template has a Name tag of `Name: ${Environment}-ecs-xx` but i want that to be `Name: ${Environment}-${cluster}-ecs-xx`. We could build that functionality into the template but i feel it would be something we'd repeat in a lot of templates.

Some example config for setting tags

```yaml
Tags:
  Project: myApp # Tag is added to all resources that can have tags
  EcsAsg: # Resource Name
    Name: 
      Sub: ${Environment}-${Cluster}-ecs-xx
```

Also the ability to set global tags across all resources that could contain tags would be a good thing to have as well. However that maybe a difficult task as not all cloudformation resources use the `Tag` property to declare tags
