### ISSUE TITLE
when inlining a component template the nested stack also gets included when the name of the component has a underscore or hypenen in the name

### ISSUE THREAD

**Issue by aaronwalker** [theonestack/cfhighlander#74]
For example

```ruby
CfhighlanderTemplate do
     Component template: 'c2', name: 'c3-test',  render: Inline
end
```
renders

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  c3test:
    Properties:
      TemplateURL: "./c3-test.compiled.yaml"
      Parameters:
        c1OutParam:
          Ref: c3testc1OutParam
    Condition: Enablec3test
    Type: AWS::CloudFormation::Stack
  Bucket:
    Properties:
      BucketName:
        Fn::Join:
        - ''
        - - Ref: c3testc1OutParam
          - "-c2"
    Type: AWS::S3::Bucket
Parameters:
  Enablec3test:
    Type: String
    Default: 'false'
    NoEcho: false
    AllowedValues:
    - 'true'
    - 'false'
  c3testc1OutParam:
    Type: String
    Default: ''
    NoEcho: false
Description: c4@latest - vlatest
Conditions:
  Enablec3test:
    Fn::Equals:
    - Ref: Enablec3test
    - 'true'
```
