### ISSUE TITLE
Test cases for components

### ISSUE THREAD

**Issue by Guslington** [theonestack/cfhighlander#83]
Thinking about creating test cases with config to run in travis-ci builds. For example the sqs component has some default config to create some demo queues, where as that should be handled with a tests case defined in `sqs.tests.yaml`. Then maybe a seperate command `cftest` or `cfcompile --config sqs.tests.yaml`.

**Comment by Guslington** [comment]
Example test yaml file with multiple test cases bellow. My thoughts were if we load each test case as seperate config, and compile the component into `out/tests/#{test_case_name}.compiled.yaml` or
`out/tests/#{test_case_name}/sqs.compiled.yaml`. from there we can validate and run cfn_nag on each test case.

```yaml
queues_with_default_config:
  queues:
    - name: queue1
    - name: queue2
    - name: queue3

queues_with_config_overrides:
  queues:
    -
      name: queue1
      visibility_timeout: 60
      delay_seconds: 20
      maximum_message_size: 1024
      message_retention_period: 300
      receive_message_wait_time_seconds: 120
    -
      name: queue2
      visibility_timeout: 120
      delay_seconds: 60
      maximum_message_size: 256
      message_retention_period: 84600
      receive_message_wait_time_seconds: 600

queues_with_fifo:
  queues:
    -
      name: queue1
      fifo_queue: true
      content_based_deduplication: true
    -
      name: queue2
      fifo_queue: true

queues_with_dlq:
  queues:
    -
      name: my-queue
      message_retention_period: 600
      redrive_policy:
        queue: my-queue-dlq
        count: 10
    -
      name: my-queue-dlq
      message_retention_period: 84600
```

**Comment by Guslington** [comment]
@toshke @aaronwalker I've implemented the cftest command on my for [fork]( https://github.com/Guslington/cfhighlander/pull/new/feature/component-test) and some test cases on the [sqs component](https://github.com/Guslington/hl-component-sqs/pull/new/feature/tests) in sqs.tests.yaml

This is pretty basic testing, loading in test case config and looping over each test case generating a template and outputing to `out/test/{test_case}/sqs.compiled/yaml`. Then running validate and catching any validate errors.

Then print out the status at the end with the correct error code
```
  ============================
  #    CfHighlander Tests    #
  ============================

  Pass: 3
  Fail: 1

  ======= FAILURES ========
  Test: queues_with_dlq
  Type: Validation
  Message: Template format error: Resource name my-queue is non alphanumeric.
```

**Comment by toshke** [comment]
@Guslington 

It is great idea overall, stepping quality gate a notch up from `this component compiles on latest developer version` would be good.  Since there is separate command to test the components, i'm not worried about potential name collisions etc. 

Few comments though,

1. Not sure if correct approach, but rather to enforce file name to `componentname.tests.yaml`, I would make this default behaviour with allowing any file with `*.tests.yaml` within component folder to be acceptable as test file. With this approach, each file would be just a config, rather than map of configs. It could be just me, but I like different tests split into separate files. Think of SCM implications of having 10 tests and single file, would be hard to track history of single test case

2. https://github.com/theonestack/cfhighlander/compare/develop...Guslington:feature/component-test?expand=1#diff-e3f178d0aee7237d7ffe28dda9c0f37dR202

Since testing will be headless most of the time, I would just enforce silent mode here.

**Comment by aaronwalker** [comment]
@toshke @Guslington My thoughts is that the test config files should be in a `tests/` directory to make it easier to see the default config regardless

**Comment by Guslington** [comment]
@toshke @aaronwalker I've updated the fork with the changes to get tests from a sub directory. This will default to `tests/` but can be overridden using the `-d,--directory` option. You can also pass in an array of tests using `-t,--test` using the relative path. `-t tests/x.test.yaml tests/y.tests.yaml`

I've update the sqs branch with example test cases.

I have also added a metadata section to add some details about the test. The test process uses the `name` section for reporting.

```yaml
test_metadata:
  type: config
  name: my test name
  description: |
    This is a long description of
    my test.
```

I will add the doco to the readme once we're happy with it and probably a shortcut command for `cftest`
